# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductsList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductsList
  pod 'Elephant-Parade'
  pod 'FSPagerView'
  pod 'FanMenu'
  pod 'RealmSwift'
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'CollectionViewSlantedLayout'

  target 'ProductsListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
